"""Radicale subprocess supervisor.

Radicale is a Python CalDAV/CardDAV server we embed for the standalone
Outlook path. We run it as a subprocess rather than an in-process thread
because (a) its default server uses signal handlers that are unreliable
under a background daemon on Windows, and (b) a subprocess boundary means
a Radicale crash can't take GBridge down.

Lifecycle (called from `gbridge.daemon`):
    supervisor = RadicaleSupervisor(config)
    supervisor.start()            # spawns python -m radicale
    assert supervisor.is_healthy(timeout=5.0)
    ...
    supervisor.stop()             # SIGTERM -> wait -> SIGKILL

All paths are under ``%LOCALAPPDATA%/gbridge/dav/`` (Windows) or
``~/.local/share/gbridge/dav/`` elsewhere, derived from Settings.
"""

from __future__ import annotations

import logging
import os
import socket
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path  # noqa: TC003 - used at runtime by RadicaleConfig dataclass

logger = logging.getLogger(__name__)


# Radicale config template — all paths are substituted at runtime.
_RADICALE_CONFIG = """\
# Autogenerated by GBridge — do not edit manually.

[server]
hosts = {host}:{port}

[auth]
type = none

[rights]
type = none

[storage]
filesystem_folder = {storage_dir}
hook =

[logging]
level = warning
"""


@dataclass
class RadicaleConfig:
    """Inputs needed to spawn a Radicale subprocess."""

    host: str
    port: int
    storage_dir: Path
    config_path: Path
    pid_path: Path
    log_path: Path


class RadicaleSupervisor:
    """Start / health-check / stop a Radicale subprocess."""

    def __init__(self, config: RadicaleConfig) -> None:
        self._config = config
        self._process: subprocess.Popen[bytes] | None = None

    # ---- public surface ----------------------------------------------------

    def start(self) -> None:
        """Write config, clear stale pidfile, spawn Radicale."""
        self._ensure_directories()
        self._write_config()

        # Clean any stale pidfile — we supervise our own process.
        if self._config.pid_path.exists():
            try:
                self._config.pid_path.unlink()
            except OSError:
                logger.debug("Failed to unlink stale pidfile")

        cmd = [
            sys.executable,
            "-m",
            "radicale",
            "--config",
            str(self._config.config_path),
        ]
        logger.info("Starting Radicale: %s", " ".join(cmd))
        # Keep the subprocess attached to us so it dies if we die.
        # On Windows CREATE_NEW_PROCESS_GROUP isolates the signal handling.
        creationflags = 0
        if sys.platform == "win32":
            creationflags = getattr(subprocess, "CREATE_NEW_PROCESS_GROUP", 0)

        log_file = self._config.log_path.open("ab")
        self._process = subprocess.Popen(  # noqa: S603 - cmd built from our own code
            cmd,
            stdin=subprocess.DEVNULL,
            stdout=log_file,
            stderr=log_file,
            close_fds=True,
            creationflags=creationflags,
        )
        self._write_pid(self._process.pid)

    def is_healthy(self, timeout: float = 5.0) -> bool:
        """Return True once Radicale answers on its port."""
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            if self._process is not None and self._process.poll() is not None:
                logger.error(
                    "Radicale exited early with code %d", self._process.returncode
                )
                return False
            if self._probe_port():
                return True
            time.sleep(0.2)
        return False

    def stop(self, *, grace_seconds: float = 5.0) -> None:
        """Terminate the subprocess, force-killing if it overstays grace."""
        if self._process is None:
            return
        proc = self._process
        if proc.poll() is not None:
            self._remove_pid()
            self._process = None
            return

        logger.info("Stopping Radicale (pid=%d)", proc.pid)
        try:
            proc.terminate()
        except OSError:
            logger.exception("Failed to SIGTERM Radicale")

        try:
            proc.wait(timeout=grace_seconds)
        except subprocess.TimeoutExpired:
            logger.warning(
                "Radicale did not exit in %.1fs, killing", grace_seconds
            )
            try:
                proc.kill()
                proc.wait(timeout=grace_seconds)
            except (OSError, subprocess.TimeoutExpired):
                logger.exception("Failed to kill Radicale cleanly")

        self._remove_pid()
        self._process = None

    @property
    def pid(self) -> int | None:
        if self._process is None:
            return None
        return self._process.pid

    # ---- internals ---------------------------------------------------------

    def _ensure_directories(self) -> None:
        self._config.storage_dir.mkdir(parents=True, exist_ok=True)
        self._config.config_path.parent.mkdir(parents=True, exist_ok=True)
        self._config.pid_path.parent.mkdir(parents=True, exist_ok=True)
        self._config.log_path.parent.mkdir(parents=True, exist_ok=True)

    def _write_config(self) -> None:
        content = _RADICALE_CONFIG.format(
            host=self._config.host,
            port=self._config.port,
            storage_dir=self._config.storage_dir.as_posix(),
        )
        self._config.config_path.write_text(content, encoding="utf-8")

    def _write_pid(self, pid: int) -> None:
        try:
            self._config.pid_path.write_text(str(pid), encoding="utf-8")
        except OSError:
            logger.warning("Failed to write pidfile %s", self._config.pid_path)

    def _remove_pid(self) -> None:
        try:
            if self._config.pid_path.exists():
                self._config.pid_path.unlink()
        except OSError:
            logger.debug("Failed to remove pidfile")

    def _probe_port(self) -> bool:
        try:
            with socket.create_connection(
                (self._config.host, self._config.port), timeout=0.5
            ):
                return True
        except OSError:
            return False


# ---- helpers -----------------------------------------------------------


def make_config(
    *,
    host: str,
    port: int,
    data_dir: Path,
) -> RadicaleConfig:
    """Assemble a RadicaleConfig under `data_dir/dav`."""
    root = data_dir / "dav"
    return RadicaleConfig(
        host=host,
        port=port,
        storage_dir=root / "collections",
        config_path=root / "radicale.conf",
        pid_path=root / "radicale.pid",
        log_path=root / "radicale.log",
    )


def read_pid(pid_path: Path) -> int | None:
    """Best-effort read of a pidfile written by a previous process."""
    try:
        return int(pid_path.read_text(encoding="utf-8").strip())
    except (OSError, ValueError):
        return None


def is_pid_alive(pid: int) -> bool:
    """Cross-platform 'is this PID still running'."""
    if pid <= 0:
        return False
    if sys.platform == "win32":
        try:
            import ctypes

            process_query_limited_information = 0x1000
            h = ctypes.windll.kernel32.OpenProcess(
                process_query_limited_information, False, pid
            )
            if not h:
                return False
            ctypes.windll.kernel32.CloseHandle(h)
            return True
        except OSError:
            return False
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    return True
